# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    Genesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            ORGNAMEConsortium:
                Organizations:
                    - *ORGNAME
                    - *Supplier
    CHANNEL_PROFILE:
        Consortium: ORGNAMEConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *ORGNAME
                - *Supplier

################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    # SampleOrg defines an MSP using the sampleconfig.  It should never be used
    # in production but may be used as a template for other definitions
    - &OrdererOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: ORGNAMEOrderer

        # ID to load the MSP definition as
        ID: ORGNAMEOrderer

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: /home/ubuntu/cryptoconfig/ordererOrganizations/ORGNAME/orderers/orderer.ORGNAME/msp
        # MSPDir: crypto-config/ordererOrganizations/example.com/msp
        AdminPrincipal: Role.ADMIN


    - &ORGNAME
        # DefaultOrg defines the organization which is used in the sampleconfig   #Enroll and Register a user called nodeAdmin. This will be the admin user for the organization.

        # of the fabric.git development environment
        Name: ORGNAME

        # ID to load the MSP definition as
        ID: ORGNAME
        # MSPDir: crypto-config/peerOrganizations/org1.example.com/msp
        MSPDir: /home/ubuntu/cryptoconfig/peerOrganizations/ORGNAME/msp
        AdminPrincipal: Role.ADMIN
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.ORGNAME
              Port: 7051
    - &Supplier
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Supplier

        # ID to load the MSP definition as
        ID: Supplier
        # MSPDir: crypto-config/peerOrganizations/org1.example.com/msp
        MSPDir: /home/ubuntu/cryptoconfig/peerOrganizations/supplier/msp
        AdminPrincipal: Role.ADMIN
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer.supplier
              Port: 7051

  
################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: solo

    Addresses:
        - orderer.ORGNAME:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:
